Repository opencost/opencost, pull requests merged in 2022-03, with the labels that each got.

#1090 replace method that was erroneously removed
  pkg/cloud/awsprovider.go
Labels: bug, needs cherry pick

#1093 Make service check thread safe
  pkg/cloud/awsprovider.go
  pkg/cloud/azureprovider.go
  pkg/cloud/provider.go
Labels: bug, patch, needs cherry pick

#1094 duplicate iterated item before taking address
  pkg/cloud/awsprovider.go
Labels: bug, patch, needs cherry pick

#1112 Use JSON-Iterator Unmarshal
  go.mod
  go.sum
  pkg/util/json/json.go
Labels: bug, patch, needs cherry pick

#1104 Changes to support ETL restructuring
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/asset.go
  pkg/kubecost/mock.go
  pkg/kubecost/query.go
  pkg/kubecost/status.go
  pkg/kubecost/summaryallocation.go
  pkg/kubecost/totals.go
  pkg/kubecost/window.go
Labels: next release
