Repository opencost/opencost, pull requests merged in 2022-02, with the labels that each got.

#1040 Implement AllocationSetRange.AccumulateBy
  pkg/costmodel/aggregation.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
Labels: next release

#1059 KLog Initialization Fix
  cmd/costmodel/main.go
  go.mod
  go.sum
  pkg/cmd/commands.go
Labels: patch

#1057 Cherrypick of refresh for a patch
  pkg/cloud/csvprovider.go
Labels: patch

#1051 Handle Rate Limit Responses in Prom Client
  go.mod
  go.sum
  pkg/cmd/agent/agent.go
  pkg/costmodel/router.go
  pkg/env/costmodelenv.go
  pkg/env/env.go
  pkg/prom/prom.go
  pkg/prom/ratelimitedclient_test.go
  pkg/thanos/thanos.go
  pkg/util/httputil/httputil.go
  pkg/util/timeutil/timeutil.go
  pkg/util/timeutil/timeutil_test.go
Labels: enhancement, next release

#1036 Allow accurate even sharing of PV costs for Pods that share PVCs
  pkg/costmodel/allocation.go
  pkg/costmodel/intervals.go
  pkg/costmodel/intervals_test.go
Labels: next release

#1028 Ajay tripathy add frontend interoperability
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/aggregation.go
  pkg/costmodel/router.go
Labels: next release

#1065 Fix idle filtration coefficient computation
  pkg/kubecost/summaryallocation.go
Labels: next release

#1072 nil checks and error handling for queryAthenaPaginated
  pkg/cloud/awsprovider.go
Labels: next release

#1087 Add support for additional AWS pricing regions
  pkg/cloud/awsprovider.go
Labels: patch, needs cherry pick

#1081 Prometheus Response Nil Check
  pkg/prom/prom.go
Labels: bug, next release, patch, needs cherry pick

#1074 Sanitize window duration in ComputeClusterCosts
  pkg/costmodel/cluster.go
Labels: bug, next release, patch, needs cherry pick

#1080 Go-JSON Replacement
  go.mod
  go.sum
  pkg/kubecost/allocation_test.go
  pkg/kubecost/asset_unmarshal.go
  pkg/kubecost/asset_unmarshal_test.go
  pkg/util/json/json.go
  test/clusterinfo_test.go
Labels: next release, needs cherry pick
