Repository opencost/opencost, pull requests merged in 2022-04, with the labels that each got.

#1138 Inf Idle Coeff patch
  pkg/kubecost/totals.go
  pkg/kubecost/totals_test.go
Labels: patch

#1152 switch to using buffers in key() creation
  pkg/kubecost/asset.go
Labels: next release

#1158 Updated CustomerPricing to include GTag
  pkg/cloud/provider.go
Labels: next release, v.193

#1160 Expose all klog args
  pkg/cmd/commands.go
Labels: next release, v1.93

#1168 GCP pricing loop
  pkg/cloud/gcpprovider.go
Labels: next release, v1.93

#1135 Quick solution for ETL Allocation hourly build/rebuild
  pkg/costmodel/allocation.go
  pkg/costmodel/cluster.go
  pkg/costmodel/costmodel.go
  pkg/env/costmodelenv.go
  pkg/kubecost/status.go
Labels: next release, v1.93

#1157 CacheGroup[T] Utility
  pkg/util/cache/cachegroup.go
  pkg/util/cache/cachegroup_test.go
  pkg/util/interval/intervalrunner.go
Labels: next release, v1.93

#1176 update azure sdk packages
  go.mod
  go.sum
Labels: next release

#1177 Add container path config
  pkg/cloud/azureprovider.go
  pkg/kubecost/asset.go
Labels: next release

#1178 Drop klog and migrate to logging package
  cmd/costmodel/main.go
  go.mod
  go.sum
  pkg/cloud/awsprovider.go
  pkg/cloud/azureprovider.go
  pkg/cloud/gcpprovider.go
  pkg/cloud/provider.go
  pkg/cloud/providerconfig.go
  pkg/clustercache/clustercache.go
  pkg/clustercache/clusterexporter.go
  pkg/clustercache/clusterimporter.go
  pkg/clustercache/watchcontroller.go
  pkg/cmd/agent/agent.go
  pkg/cmd/commands.go
  pkg/config/configfile.go
  pkg/config/configmanager.go
  pkg/costmodel/aggregation.go
  pkg/costmodel/allocation.go
  pkg/costmodel/cluster.go
  pkg/costmodel/cluster_helpers.go
  pkg/costmodel/clusterinfo.go
  pkg/costmodel/clusters/clustermap.go
  pkg/costmodel/costmodel.go
  pkg/costmodel/metrics.go
  pkg/costmodel/promparsers.go
  pkg/costmodel/router.go
  pkg/costmodel/settings.go
  pkg/costmodel/sql.go
  pkg/env/costmodelenv.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocationprops.go
  pkg/kubecost/asset.go
  pkg/kubecost/summaryallocation.go
  pkg/log/log.go
  pkg/prom/query.go
  pkg/prom/result.go
  pkg/services/clusters/clustermanager.go
  pkg/services/clusters/clustersendpoints.go
  pkg/services/clusterservice.go
  pkg/services/services.go
  pkg/util/watcher/configwatchers.go
Labels: next release, v1.93

#1131 Implement UID id of pods to fix time running inaccuracy
  pkg/costmodel/allocation.go
  pkg/env/costmodelenv.go
Labels: next release, v1.93

#1187 Add Clone to SummaryAllocationSet
  pkg/kubecost/summaryallocation.go
Labels: next release, v1.93

#1181 Concurrent Worker Package
  pkg/collections/blockingqueue.go
  pkg/kubecost/common.go
  pkg/prom/diagnostics.go
  pkg/prom/prom.go
  pkg/util/atomic/atomicbool.go
  pkg/util/worker/example_worker_test.go
  pkg/util/worker/worker.go
  pkg/util/worker/worker_test.go
Labels: next release, v1.93
