Repository opencost/opencost, pull requests merged in 2022-10, with the labels that each got.

#1435 Initial NOTICE based off of Apache recommendations
  NOTICE
Labels: opencost

#1438 Make usage of Disk resilient to absence of metrics
  pkg/costmodel/cluster.go
  pkg/kubecost/asset.go
  pkg/kubecost/asset_json.go
  pkg/kubecost/asset_json_test.go
  pkg/kubecost/kubecost_codecs.go
Labels: v1.98

#1448 Update golang.org/x/net and /x/text to fix CVEs
  go.mod
  go.sum
Labels: needs cherry pick, v1.98

#1445 Download pricing data in a goroutine to prevent deadlock when updating Azure configuration
  pkg/cloud/azureprovider.go
Labels: bug, next release, P0, v1.98

#1455 V1.98 patch/azure storage secret
  pkg/cloud/azureprovider.go
Labels: bug, P0, v1.98

#1454 fix condition on configuration
  pkg/cloud/azureprovider.go
Labels: bug, P0, v1.98
