Repository opencost/opencost, pull requests merged in 2022-05, with the labels that each got.

#1174 update base types to support ad hoc cloud usage queries
  pkg/cloud/provider.go
  pkg/kubecost/asset.go
  pkg/kubecost/query.go
  pkg/kubecost/status.go
Labels: next release, v1.93

#1185 Allow alloc/asset set clone of errors/warnings
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
Labels: next release, v1.93

#1179 Attribute batch/v1 CronJob controller correctly
  pkg/costmodel/costmodel.go
  pkg/costmodel/costmodel_test.go
Labels: next release, v1.93

#1194 remove prefix
  pkg/kubecost/asset.go
Labels: v1.93

#1193 Don't add gpu pricing when no gpu
  pkg/costmodel/cluster_helpers.go
  pkg/costmodel/cluster_helpers_test.go
Labels: v1.94

#1191 Collect attached volume totals by cluster
  pkg/kubecost/totals.go
Labels: v1.93

#1195 Collect attached volume totals by cluster
  pkg/kubecost/totals.go
Labels: v1.93

#1197 Switch log to debug
  pkg/kubecost/totals.go
Labels: v1.93

#1198 Add Message to a SummaryAllocationSetRange
  pkg/kubecost/summaryallocation.go
Labels: v1.93

#1199 v1.93 cherry picks: log and message
  pkg/kubecost/summaryallocation.go
  pkg/kubecost/totals.go
Labels: v1.93

#1172 Filters v2: (Allocation) in-Go representation + basic Matches() implementation
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
Labels: v1.94

#1211 Support wildcard (filterNamespaces=kube*) queries with new AllocationFilter types
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
  pkg/util/filterutil/allocationfilters.go
  pkg/util/filterutil/allocationfilters_test.go
Labels: v1.94

#1214 Cost-Model Monitoring and Diagnostic Enhancements
  go.mod
  go.sum
  pkg/cmd/agent/agent.go
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/metrics.go
  pkg/costmodel/router.go
  pkg/kubecost/common.go
  pkg/metrics/events.go
  pkg/metrics/httpmetricmiddleware.go
  pkg/metrics/telemetry.go
  pkg/prom/diagnostics.go
  pkg/util/defaults/defaults.go
  pkg/util/retry/retry.go
  pkg/util/retry/retry_test.go
Labels: next release, v1.94

#1210 Add support for translating current filters (filterNamespaces=) to the new AllocationFilter types
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
  pkg/util/filterutil/allocationfilters.go
  pkg/util/filterutil/allocationfilters_test.go
Labels: v1.94

#1219 Return results of updating totals store (for ETL events)
  pkg/kubecost/totals.go
Labels: next release, v1.94

#1216 Add provider id for PV for GCP
  pkg/cloud/gcpprovider.go
  pkg/costmodel/cluster.go
Labels: next release, v1.94

#1221 Storage Support for GCS and Azure
  go.mod
  go.sum
  pkg/storage/azurestorage.go
  pkg/storage/bucketstorage.go
  pkg/storage/filestorage.go
  pkg/storage/gcsstorage.go
  pkg/storage/s3storage.go
  pkg/storage/storage.go
  pkg/storage/storagetypes.go
  pkg/storage/storagetypes_test.go
  pkg/storage/tlsconfig.go
Labels: next release, v1.94

#1212 Add editor access item to custompricing
  pkg/cloud/provider.go
Labels: v1.94
