Repository opencost/opencost, pull requests merged in 2022-06, with the labels that each got.

#1233 Create opencost-specv01.md
  spec/opencost-specv01.md
Labels: opencost

#1253 use provider constants
  pkg/cloud/awsprovider.go
  pkg/cloud/gcpprovider.go
  pkg/cloud/provider.go
  pkg/kubecost/asset_test.go
  pkg/kubecost/asset_unmarshal_test.go
  pkg/kubecost/assetprops.go
  pkg/kubecost/kubecost_codecs_test.go
  pkg/kubecost/mock.go
Labels: v1.94

#1258 Make logging configurable with pflags
  pkg/log/log.go
Labels: v1.95

#1263 Remove InitLoggingFromFlags
  pkg/log/log.go
Labels: v1.95

#1262 Add parameter to log init: hide log level message
  pkg/cmd/commands.go
  pkg/log/log.go
Labels: v1.95

#1269 Update KubeConfig Loader with Auth Import
  pkg/kubeconfig/loader.go
Labels: v1.95

#1272 Export mapper.GoMap and add constructor
  pkg/util/mapper/mapper.go
Labels: v1.95

#1250 Lexer and Parser for v2 of the Allocation filter language
  go.mod
  go.sum
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
  pkg/util/allocationfilterutil/queryfilters.go
  pkg/util/allocationfilterutil/queryfilters_test.go
  pkg/util/allocationfilterutil/v2/lexer.go
  pkg/util/allocationfilterutil/v2/lexer_test.go
  pkg/util/allocationfilterutil/v2/parser.go
  pkg/util/allocationfilterutil/v2/parser_test.go
Labels: v1.95

#1273 Add AllocationFilter.Flattened() for simplifying AllocationFilter expressions
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
Labels: v1.95

#1279 Support GCP Spot VMs
  pkg/cloud/gcpprovider.go
  pkg/cloud/gcpprovider_test.go
Labels: v1.95

#1213 Audit and Generic Store types
  pkg/costmodel/router.go
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
  pkg/kubecost/audit.go
  pkg/kubecost/bingen.go
  pkg/kubecost/etlrange.go
  pkg/kubecost/etlset.go
  pkg/kubecost/kubecost_codecs.go
  pkg/kubecost/totals.go
  pkg/kubecost/window.go
Labels: v1.95
