Repository opencost/opencost, pull requests merged in 2022-07, with the labels that each got.

#1293 Use Query offset in raw query, fix file name of local cluster
  pkg/costmodel/clusters/clustermap.go
  pkg/costmodel/router.go
  pkg/prom/query.go
Labels: bug, v1.95, P0

#1304 V1.95 patch/fix cluster map on hosted
  pkg/costmodel/clusters/clustermap.go
  pkg/costmodel/router.go
  pkg/prom/query.go
Labels: bug, v1.95

#1307 Update Azure LB pricing and comment
  pkg/cloud/azureprovider.go
Labels: bug

#1309 Remove log spam related to Allocation lb queries
  pkg/costmodel/allocation.go
  pkg/costmodel/costmodel.go
  pkg/costmodel/metrics.go
Labels: bug, v1.96

#1274 Replace FilterFunc core filters with AllocationFilter
  pkg/costmodel/aggregation.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
  pkg/kubecost/query.go
  pkg/kubecost/summaryallocation.go
Labels: v1.96

#1290 Update slack links to CNCF
  CONTRIBUTING.md
  README.md
Labels: CNCF

#1322 Add Azure Storage Config values to provider config
  pkg/cloud/azureprovider.go
  pkg/cloud/provider.go
  pkg/costmodel/allocation.go
  pkg/costmodel/router.go
Labels: v1.96

#1334 Update bingen asset version number, fix adjustment field on cluster m…
  pkg/kubecost/asset.go
  pkg/kubecost/bingen.go
  pkg/kubecost/kubecost_codecs.go
Labels: bug, v1.95

#1294 Add Pod Name Environment Variable
  pkg/env/costmodelenv.go
Labels: v1.96

#1337 check secret for values on first load of rate card
  pkg/cloud/azureprovider.go
Labels: bug, v1.96
