Repository opencost/opencost, pull requests merged in 2022-12, with the labels that each got.

#1529 Reduce log level of metric parsing warnings in ClusterDisks
  pkg/costmodel/cluster.go
Labels: v1.99

#1530 Reduce log level of metric parsing warnings in ClusterDisks
  pkg/costmodel/cluster.go
Labels: needs cherry pick, v1.99

#1541 Fix ListDirectories for GCS not working properly
  pkg/storage/gcsstorage.go
Labels: needs cherry pick, v1.99

#1537 Taking into account Summary Allocation not run for entire duration of SAS set window for RAM and CPU efficiency calculation
  pkg/kubecost/summaryallocation.go
  pkg/kubecost/summaryallocation_test.go
Labels: bug, needs cherry pick, v1.99

#1539 Noticed a Panic during system disk retrieval for a node when Alibaba service key is not given
  pkg/cloud/aliyunprovider.go
Labels: bug, needs cherry pick, v1.99

#1574 Allow ui to run from non privileged
  ui/Dockerfile
  ui/default.nginx.conf
  ui/nginx.conf
Labels: opencost

#1577 feat(metrics): Add opencost_build_info metric
  Makefile
  go.mod
  go.sum
  pkg/metrics/telemetry.go
  tools/image-tag
Labels: opencost, v1.100
