Repository opencost/opencost, pull requests merged in 2022-08, with the labels that each got.

#1328 Diff asset tracks cost changes
  pkg/kubecost/asset.go
  pkg/kubecost/diff_test.go
Labels: v1.96

#1343 filter shared assets in aggby
  pkg/kubecost/asset.go
Labels: bug, v1.96

#1345 add additional region codes
  pkg/cloud/azureprovider.go
Labels: bug, v1.96

#1348 add check to prevent nil pointer for azure storage on fresh install
  pkg/cloud/azureprovider.go
Labels: bug, v1.96

#1349 add check to prevent nil point for azure storage on fresh install
  pkg/cloud/azureprovider.go
Labels: bug, v1.96

#1347 add additional region codes
  pkg/cloud/azureprovider.go
Labels: bug, v1.96

#1346 filter shared assets in agg by
  pkg/kubecost/asset.go
Labels: bug, v1.96

#1275 Add Scaleway as a provider
  go.mod
  go.sum
  pkg/cloud/provider.go
  pkg/cloud/scalewayprovider.go
  pkg/kubecost/assetprops.go
  pkg/util/compat.go
Labels: v1.96

#1344 updated prom client to 1.12.2
  go.mod
  go.sum
  pkg/costmodel/router.go
  pkg/prom/prom.go
  pkg/prom/query.go
  pkg/prom/ratelimitedclient_test.go
Labels: v1.97

#1359 Implement .Equals() for the AllocationFilter interface
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
Labels: v1.97

#1361 Fix PV alloc recon, alloc PV marshalling
  pkg/costmodel/allocation.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_json.go
  pkg/kubecost/allocation_json_test.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/asset.go
  pkg/kubecost/asset_json.go
  pkg/kubecost/asset_json_test.go
  pkg/kubecost/mock.go
Labels: v1.97
