Repository opencost/opencost, pull requests merged in 2023-05, with the labels that each got.

#1832 Initial ADOPTERS.MD to list organizations using OpenCost
  ADOPTERS.MD
Labels: opencost, CNCF

#1924 Avoid panic in AWS findCostForDisk
  pkg/cloud/aws/provider.go
Labels: v1.104

#1932 Move Athena CloudCost integration to OpenCost
  pkg/cloud/aws/athenaconfiguration.go
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/athenaintegration_test.go
  pkg/cloud/aws/athenaquerier.go
  pkg/cloud/cloudcostintegration.go
  pkg/cloud/connectionstatus.go
  pkg/kubecost/bingen.go
  pkg/kubecost/kubecost_codecs.go
Labels: v1.104

#1933 Ajay tripathy combined fixes
  config/invalid.json
  configs/pricing_schema_pv_storageclass.csv
  configs/pricing_schema_special_char.csv
  pkg/cloud/provider/csvprovider.go
  pkg/metrics/kubemetrics.go
  test/cloud_test.go
Labels: v1.104

#1945 Remove temp file on test completion
  pkg/filemanager/filemanager_test.go
Labels: v1.104

#1949 Upgrade go-restful/v3 to v3.10
  go.mod
  go.sum
Labels: v1.104

#1430 added current cluster id filter
  pkg/cloud/gcp/provider.go
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
  pkg/costmodel/cluster.go
  pkg/costmodel/clusters/clustermap.go
  pkg/costmodel/costmodel.go
  pkg/env/costmodelenv.go
  pkg/prom/diagnostics.go
  pkg/util/allocationfilterutil/v2/parser.go
Labels: opencost

#1956 Added Azure CUR integration to the Open Source.
  pkg/cloud/azure/azurestorageintegration.go
  pkg/cloud/azure/azurestorageintegration_test.go
Labels: v1.104

#1959 Added Azure CUR integration to the Open Source.
  pkg/cloud/azure/azurestorageintegration.go
  pkg/cloud/azure/azurestorageintegration_test.go
Labels: v1.104
