Repository opencost/opencost, pull requests merged in 2023-10, with the labels that each got.

#2199 Improve AWS integrations
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/athenaquerier.go
  pkg/cloud/aws/s3selectintegration.go
Labels: v1.106

#2209 Emit empty string instead of <none> for storageclass label on kube_persistentvolumeclaim_info to match KSM changes
  pkg/metrics/kubemetrics.go
Labels: v1.107

#2189 scaleway :: fix gpu value
  pkg/cloud/scaleway/provider.go
Labels: opencost, P1, E2

#2177 fix: use spot label nodes from custom provider config
  pkg/cloud/aws/provider.go
  pkg/cloud/aws/provider_test.go
Labels: opencost, P1, kubecost, E3

#2165 csv export: override default max days (default: 90d)
  pkg/costmodel/allocation.go
  pkg/env/costmodelenv.go
  pkg/env/costmodelenv_test.go
Labels: opencost, P1, E2

#1931 AWS EBS: add default EBS volume types for provisioners
  pkg/cloud/aws/provider.go
  pkg/cloud/aws/provider_test.go
Labels: opencost, P1, kubecost, E2

#2211 Implement Clone() for NodeOverhead so it shows up in accumulated results
  pkg/kubecost/asset.go
  pkg/kubecost/asset_test.go
  pkg/kubecost/assetprops.go
Labels: next release

#2170 prevent error on catalog missing from config
  pkg/cloud/aws/athenaconfiguration.go
Labels: v1.107

#2251 Nil out overhead when adding nil to non-nil
  pkg/kubecost/asset.go
  pkg/kubecost/asset_test.go
Labels: v1.107

#2258 Fix cloud status endpoint for aggregator
  pkg/cloud/alibaba/boaquerier.go
  pkg/cloud/aws/athenaconfiguration.go
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/athenaquerier.go
  pkg/cloud/aws/s3configuration.go
  pkg/cloud/aws/s3connection.go
  pkg/cloud/azure/azurestorageintegration.go
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconfiguration.go
  pkg/cloud/azure/storageconnection.go
  pkg/cloud/cloudcostintegration.go
  pkg/cloud/gcp/bigqueryconfiguration.go
  pkg/cloud/gcp/bigqueryquerier.go
Labels: v1.107

#2261 fix bug where err is not returned from query
  pkg/cloud/gcp/bigqueryquerier.go
Labels: v1.107

#2263 replace missing func
  pkg/cloud/aws/athenaintegration.go
Labels: v1.107
