Repository opencost/opencost, pull requests merged in 2023-06, with the labels that each got.

#1976 Sanitize old nil sample AWS access key value
  pkg/cloud/aws/provider.go
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/providerconfig.go
  pkg/env/costmodelenv.go
Labels: needs cherry pick, v1.104

#1977 V1.104 patch/burndown 144
  pkg/cloud/aws/provider.go
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/providerconfig.go
  pkg/env/costmodelenv.go
Labels: v1.104

#1978 V1.104 patch/close s3files
  pkg/storage/s3storage.go
Labels: v1.104

#1970 Add filter v2.1 scaffolding
  pkg/filter21/ast/fields.go
  pkg/filter21/ast/lexer.go
  pkg/filter21/ast/lexer_test.go
  pkg/filter21/ast/ops.go
  pkg/filter21/ast/parser.go
  pkg/filter21/ast/tree.go
  pkg/filter21/ast/walker.go
  pkg/filter21/filter.go
  pkg/filter21/matcher/allcut.go
  pkg/filter21/matcher/allpass.go
  pkg/filter21/matcher/and.go
  pkg/filter21/matcher/compiler.go
  pkg/filter21/matcher/matcher.go
  pkg/filter21/matcher/not.go
  pkg/filter21/matcher/or.go
  pkg/filter21/matcher/stringmapmatcher.go
  pkg/filter21/matcher/stringmatcher.go
  pkg/filter21/matcher/stringslicematcher.go
  pkg/filter21/transform/pass.go
  pkg/filter21/transform/promlabels.go
  pkg/filter21/transform/unallocated.go
  pkg/filter21/util/stack.go
Labels: v1.105

#1971 Implement v2.1 filtering logic for Allocation
  pkg/filter21/allocation/fields.go
  pkg/filter21/allocation/parser.go
  pkg/filter21/allocation/parser_test.go
  pkg/filter21/ast/fields.go
  pkg/filter21/ast/tree.go
  pkg/filter21/matcher/matcher_test.go
  pkg/filter21/ops/ops.go
  pkg/filter21/ops/ops_test.go
  pkg/kubecost/allocationmatcher.go
  pkg/util/typeutil/typeutil.go
Labels: v1.105

#1973 Add "Container" to Breakdown options for OpenCost UI
  ui/src/Reports.js
Labels: opencost

#1982 Switch Allocation filters to v2.1
  pkg/filter/cloudcost/cloudcost.go
  pkg/filter/cloudcost/cloudcost_test.go
  pkg/filter21/ast/ops.go
  pkg/filter21/ast/walker.go
  pkg/filter21/matcher/compiler.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/allocationfilter.go
  pkg/kubecost/allocationfilter_test.go
  pkg/kubecost/query.go
  pkg/kubecost/summaryallocation.go
  pkg/util/allocationfilterutil/queryfilters.go
  pkg/util/allocationfilterutil/v2/lexer.go
  pkg/util/allocationfilterutil/v2/lexer_test.go
  pkg/util/allocationfilterutil/v2/parser.go
  pkg/util/allocationfilterutil/v2/parser_test.go
  pkg/util/filterutil/filterutil.go
  pkg/util/filterutil/queryfilters_test.go
  pkg/util/filterutil/testhelpers.go
  pkg/util/filterutil/v1.go
  pkg/util/filterutil/v1_test.go
Labels: v1.105

#1985 Add Alias support to v2.1 Allocation filters
  pkg/filter21/allocation/fields.go
  pkg/filter21/allocation/parser.go
  pkg/filter21/ast/tree.go
  pkg/filter21/ast/walker.go
  pkg/filter21/ast/walker_test.go
  pkg/filter21/matcher/compiler.go
  pkg/filter21/ops/ops_test.go
  pkg/filter21/transform/pass.go
  pkg/filter21/transform/promlabels.go
  pkg/filter21/transform/unallocated.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/allocationfilter_test.go
  pkg/kubecost/allocationmatcher.go
  pkg/kubecost/allocationmatcher_test.go
  pkg/kubecost/summaryallocation.go
  pkg/util/filterutil/filterutil.go
  pkg/util/filterutil/queryfilters_test.go
Labels: v1.105

#1947 Enabling UI image to run as non-root
  ui/Dockerfile
Labels: v1.105

#1995 Switch Assets to v2.1 filters
  pkg/filter21/asset/fields.go
  pkg/filter21/asset/parser.go
  pkg/filter21/ast/walker.go
  pkg/filter21/matcher/compiler.go
  pkg/kubecost/allocationmatcher.go
  pkg/kubecost/allocationmatcher_test.go
  pkg/kubecost/asset.go
  pkg/kubecost/assetmatcher.go
  pkg/kubecost/cloudusage.go
  pkg/kubecost/query.go
  pkg/util/filterutil/asset_test.go
  pkg/util/filterutil/filterutil.go
  pkg/util/filterutil/queryfilters_test.go
Labels: v1.105

#2011 Sean/lb private bingen
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
  pkg/kubecost/bingen.go
  pkg/kubecost/kubecost_codecs.go
Labels: v1.105

#2012 V1.105 patch/bingen fixes
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
  pkg/kubecost/bingen.go
  pkg/kubecost/kubecost_codecs.go
Labels: v1.105
