Repository opencost/opencost, pull requests merged in 2023-02, with the labels that each got.

#1647 Set up Karpenter capacity type label
  pkg/cloud/awsprovider.go
  pkg/cloud/awsprovider_test.go
  pkg/cloud/gcpprovider.go
  pkg/cloud/gcpprovider_test.go
  pkg/cloud/provider.go
Labels: v1.100

#1630 Add support for prefix parameter in bucket config
  pkg/storage/bucketstorage.go
  pkg/storage/prefixedbucketstorage.go
Labels: v1.100

#1687 Fix panic in Asset/AllocSetRange NewAccumulation
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
Labels: v1.100

#1673 add favicon to OpenCost UI
  pkg/kubecost/allocation_json.go
  ui/src/images/favicon.ico
  ui/src/index.html
Labels: opencost

#1696 Fix incorrect value in node vgpu count assignment for vGPUs
  pkg/costmodel/costmodel.go
Labels: v1.101

#1707 Fix ListDirectories for Azure Storage
  pkg/storage/azurestorage.go
Labels: v1.101

#1698 Specify units of some CustomPricing fields
  pkg/cloud/provider.go
Labels: v1.101
