Repository opencost/opencost, pull requests merged in 2023-08, with the labels that each got.

#2083 GTM-52 Fix parsing of GCP pricing and create new node diagnostic pricing API
  pkg/cloud/alibaba/provider.go
  pkg/cloud/aws/provider.go
  pkg/cloud/azure/provider.go
  pkg/cloud/gcp/provider.go
  pkg/cloud/gcp/provider_test.go
  pkg/cloud/gcp/test/skus.json
  pkg/cloud/models/models.go
  pkg/cloud/models/pricing.go
  pkg/cloud/provider/csvprovider.go
  pkg/cloud/provider/customprovider.go
  pkg/cloud/scaleway/provider.go
  pkg/costmodel/costmodel.go
  test/cloud_test.go
Labels: needs cherry pick, v1.106

#2107 GTM-63 sanitize label names before metric emission to prevent label name collisions
  pkg/metrics/deploymentmetrics.go
  pkg/metrics/namespacemetrics.go
  pkg/metrics/nodemetrics.go
  pkg/metrics/podlabelmetrics.go
  pkg/metrics/podmetrics.go
  pkg/metrics/servicemetrics.go
  pkg/metrics/statefulsetmetrics.go
  pkg/metrics/telemetry.go
  pkg/prom/metrics.go
  pkg/prom/metrics_test.go
Labels: v1.106

#2108 GTM-63 sanitize label names before metric emission to prevent label name collisions
  pkg/metrics/deploymentmetrics.go
  pkg/metrics/namespacemetrics.go
  pkg/metrics/nodemetrics.go
  pkg/metrics/podlabelmetrics.go
  pkg/metrics/podmetrics.go
  pkg/metrics/servicemetrics.go
  pkg/metrics/statefulsetmetrics.go
  pkg/metrics/telemetry.go
  pkg/prom/metrics.go
  pkg/prom/metrics_test.go
Labels: v1.106

#2118 BURNDOWN-209 fix Inf and negative values in pod-to-PVC attribution
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
  pkg/costmodel/intervals.go
  pkg/costmodel/intervals_test.go
Labels: v1.106

#1801 disabled healthz endpoint logging
  ui/default.nginx.conf
Labels: opencost

#1991 Add custom S3 CSV billing export endpoint
  pkg/filemanager/filemanager.go
Labels: opencost

#2122 Remove default values for GCP cloud billing integration
  configs/gcp.json
Labels: v1.107
