Repository opencost/opencost, pull requests merged in 2023-12, with the labels that each got.

#2357 add profiling endpoints
  pkg/cmd/costmodel/costmodel.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up

#2354 fix test, add defensive check to scaleway
  pkg/cloud/scaleway/provider.go
  pkg/cloudcost/memoryrepository_test.go
Labels: needs-follow-up

#2362 sanitize asset labels
  pkg/costmodel/cluster_helpers.go
  pkg/costmodel/cluster_helpers_test.go
  pkg/kubecost/asset.go
Labels: needs-follow-up

#2364 sanitize asset labels
  pkg/costmodel/cluster_helpers.go
  pkg/costmodel/cluster_helpers_test.go
  pkg/kubecost/asset.go
Labels: v1.106, needs-follow-up

#2363 Support for Azure Workload Identities
  pkg/cloud/azure/authorizer.go
  pkg/cloud/azure/storageauthorizer.go
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconfiguration.go
  pkg/cloud/azure/storageconfiguration_test.go
  pkg/cloud/azure/storageconnection.go
  pkg/cloud/config/configurations_test.go
Labels: v1.108, needs-follow-up

#2366 Expose and make the API and UI ports configurable
  pkg/cmd/costmodel/costmodel.go
  pkg/env/costmodelenv.go
  pkg/env/costmodelenv_test.go
  ui/Dockerfile
  ui/Dockerfile.cross
  ui/default.nginx.conf.template
  ui/docker-entrypoint.sh
Labels: next release, opencost, P2, E3, needs-follow-up

#2350 Cleaner logging in metrics.go
  pkg/costmodel/costmodel.go
  pkg/costmodel/metrics.go
Labels: opencost, P2, E2, needs-follow-up

#2373 update Dockerfile.cross with new default.nginx.conf.template
  ui/Dockerfile.cross
Labels: v1.108, needs-follow-up

#2374 update dockerfile.cross with new nginx.conf.template
  ui/Dockerfile.cross
Labels: v1.108

#2371 Add labels to cloud cost view table rows
  pkg/cloudcost/querier.go
  pkg/cloudcost/queryservice.go
  pkg/cloudcost/repositoryquerier.go
  pkg/cloudcost/view.go
Labels: v1.108, needs-follow-up

#2376 aggregate by all if aggregate is empty
  pkg/cloudcost/queryservice_helper.go
  pkg/cloudcost/queryservice_helper_test.go
Labels: needs-follow-up

#2378 Pick #2376 for v1.108
  pkg/cloudcost/queryservice_helper.go
  pkg/cloudcost/queryservice_helper_test.go
Labels: needs-follow-up

#2375 Extends: Fixes drilldown per item day and descending order on agg by item - PR #2289
  .gitignore
  ui/src/cloudCost/cloudCostDetails.js
  ui/src/cloudCostReports.js
  ui/src/services/cloudCostDayTotals.js
  ui/src/services/cloudCostTop.js
  ui/src/util.js
Labels: needs-follow-up

#2379 Pick #2375 for v1.108
  .gitignore
  ui/src/cloudCost/cloudCostDetails.js
  ui/src/cloudCostReports.js
  ui/src/services/cloudCostDayTotals.js
  ui/src/services/cloudCostTop.js
  ui/src/util.js
Labels: needs-follow-up

#2299 Handle SUSE Rancher node special case
  pkg/costmodel/costmodel.go
Labels: needs-follow-up

#2385 Log and continue on a single record processing failures.
  pkg/costmodel/costmodel.go
Labels: needs-follow-up

#2372 Add Artur Khantimirov to the OpenCost Maintainers
  MAINTAINERS.md
Labels: opencost, CNCF, needs-follow-up

#2388 feat: 2323 adding version and commit on opencost-ui logs
  ui/Dockerfile
  ui/Dockerfile.cross
  ui/docker-entrypoint.sh
  ui/justfile
Labels: needs-follow-up

#2387 update Tiltfile to support nginx template change
  Tiltfile
Labels: needs-follow-up

#2319 Configure Dependabot to update NPM dependencies under /ui
  .github/dependabot.yml
Labels: opencost, P2, E1

#2397 dump the gh context for debugging
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2398 Atm/debug code cov
  .github/workflows/build-test.yaml
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2395 [DO NOT MERGE] testing sonar code coverage
  .github/workflows/build-test.yaml
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2399 Revert "[DO NOT MERGE] testing sonar code coverage"
  .github/workflows/build-test.yaml
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2400 run baseline scan when on develop
  .github/workflows/build-test.yaml
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2402 additional settings
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2396 Allocation properties: Add support for aliased labels
  pkg/kubecost/allocationprops.go
Labels: needs-follow-up

#2403 rm bad branch
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2404 Atm/undo bad params
  .github/workflows/sonar.yaml
Labels: needs-follow-up

#2406 add sonar-project.properties
  sonar-project.properties
Labels: needs-follow-up

#2408 Enable (*FileStorage).ListDirectories to list symlinks which target directories
  pkg/storage/filestorage.go
  pkg/storage/filestorage_test.go
Labels: needs-follow-up

#2409 Make telemetry metrics respect disable state
  pkg/costmodel/metrics.go
  pkg/metrics/telemetry.go
Labels: next release, needs-follow-up

#2413 Pick #2409 for v1.108
  pkg/costmodel/metrics.go
  pkg/metrics/telemetry.go
Labels: needs-follow-up

#2414 Dependabot updates
  go.mod
  go.sum
Labels: needs-follow-up
