Repository opencost/opencost, pull requests merged in 2023-04, with the labels that each got.

#1837 Update windows helper function to support weekly resolution
  pkg/kubecost/window.go
Labels: v1.102

#1792 Add functionality to export opencost data to a CSV file in cloud storage.
  go.mod
  go.sum
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/allocation.go
  pkg/costmodel/csv_export.go
  pkg/costmodel/csv_export_test.go
  pkg/costmodel/moq_allocation_model_test.go
  pkg/env/costmodelenv.go
  pkg/filemanager/filemanager.go
  pkg/filemanager/filemanager_test.go
  pkg/storage/azurestorage.go
Labels: opencost, doc needed

#1842 Support for Azure consumption pricesheet download API
  go.mod
  go.sum
  pkg/cloud/azurepricesheet/client.go
  pkg/cloud/azurepricesheet/downloader.go
  pkg/cloud/azurepricesheet/downloader_test.go
  pkg/cloud/azureprovider.go
  pkg/cloud/azureprovider_test.go
  pkg/cloud/provider.go
  pkg/env/costmodelenv.go
Labels: opencost

#1843 Updated description of community meeting to please CLOMonitor
  README.md
Labels: opencost, CNCF

#1844 Update to include OpenCost cost-model and UI, minor other fixes
  CONTRIBUTING.md
Labels: opencost

#1858 Partially handle Azure Virtual Nodes (serverless)
  pkg/cloud/azureprovider.go
  pkg/costmodel/allocation_helpers.go
Labels: needs cherry pick, v1.103

#1865 Single Cloud Cost type
  pkg/filter/util/cloudcost.go
  pkg/filter/util/cloudcostaggregate.go
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
  pkg/kubecost/bingen.go
  pkg/kubecost/cloudcost.go
  pkg/kubecost/cloudcost_test.go
  pkg/kubecost/cloudcostaggregate.go
  pkg/kubecost/cloudcostaggregate_test.go
  pkg/kubecost/cloudcostitem.go
  pkg/kubecost/cloudcostitem_test.go
  pkg/kubecost/cloudcostprops.go
  pkg/kubecost/cloudcostprops_test.go
  pkg/kubecost/kubecost_codecs.go
  pkg/kubecost/mock.go
  pkg/kubecost/window.go
Labels: v1.103

#1879 New Cloud Cost types with focus spec properties
  pkg/filter/util/cloudcost.go
  pkg/filter/util/cloudcostaggregate.go
  pkg/kubecost/allocation.go
  pkg/kubecost/asset.go
  pkg/kubecost/bingen.go
  pkg/kubecost/cloudcost.go
  pkg/kubecost/cloudcost_test.go
  pkg/kubecost/cloudcostaggregate.go
  pkg/kubecost/cloudcostaggregate_test.go
  pkg/kubecost/cloudcostitem.go
  pkg/kubecost/cloudcostitem_test.go
  pkg/kubecost/cloudcostprops.go
  pkg/kubecost/cloudcostprops_test.go
  pkg/kubecost/kubecost_codecs.go
  pkg/kubecost/mock.go
  pkg/kubecost/window.go
Labels: v1.103

#1882 set providerID on custom pricing
  pkg/costmodel/allocation_helpers.go
Labels: v1.103

#1888 Set providerID on custom pricing
  pkg/costmodel/allocation_helpers.go
Labels: v1.103
