Repository opencost/opencost, pull requests merged in 2023-01, with the labels that each got.

#1592 Add endpoints to set and get log levels
  pkg/costmodel/router.go
  pkg/log/log.go
Labels: v1.100

#1594 allocation struct to have Network breakdown values of Zone, Region and Internet costs
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_json.go
  pkg/kubecost/bingen.go
  pkg/kubecost/kubecost_codecs.go
Labels: enhancement, v1.100

#1601 Use localhost resolver to get host
  ui/default.nginx.conf
Labels: v1.100

#1627 Add a unit test to v2 filter parsing for a fully-qualified DaemonSet container query
  pkg/util/allocationfilterutil/v2/parser_test.go
Labels: v1.100

#1603 remove cluster aggregation breakage
  ui/src/Reports.js
Labels: opencost

#1618 Apply node labels to allocation data
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
  pkg/costmodel/allocation_types.go
  pkg/costmodel/key.go
  pkg/env/costmodelenv.go
Labels: v1.100

#1608 fix GPU counting bug when separate GPU cost is defined but not CPU/RAM
  pkg/costmodel/costmodel.go
Labels: v1.100
