Repository opencost/opencost, pull requests merged in 2023-11, with the labels that each got.

#2160 pkg/kubecost: fix dropped test errors
  pkg/kubecost/asset_test.go
Labels: opencost, kubecost, E2, P3

#2145 pkg/costmodel: fix dropped errors
  pkg/costmodel/costmodel.go
Labels: opencost, P2, kubecost, E1

#2208 Use spot custom prices when spot node determined
  pkg/cloud/azure/provider.go
Labels: opencost, P1, kubecost, E2

#2288 Restore the standard quay.io repositories
  kubernetes/opencost.yaml
Labels: opencost, P1, E1

#2293 Simplify prometheus queries
  pkg/costmodel/costmodel.go
Labels: opencost, P1, kubecost, E2

#1861 added a separate client for prometheus scrape config endpoint
  pkg/cmd/agent/agent.go
  pkg/costmodel/allocation.go
  pkg/costmodel/router.go
  pkg/env/costmodelenv.go
Labels: opencost, P2, kubecost, E3

#2305 fix: Quote table name in Athena query to handle cases where table name does not begin with an alphabet
  pkg/cloud/aws/athenaintegration.go
Labels: opencost, P2, kubecost, E1

#2296 Amortization For GCP Cloud Cost
  pkg/cloud/gcp/bigqueryintegration.go
  pkg/cloud/gcp/bigqueryintegration_types.go
  pkg/cloud/gcp/cloudcost.go
Labels: v1.108, needs-follow-up

#2347 Updated URL and other warning messages to reflect OpenCost not Kubecost
  ui/src/cloudCostReports.js
Labels: opencost, E1, P3

#2349 Fix Read-only file system issue during CSV Export
  kubernetes/exporter/opencost-exporter.yaml
Labels: needs-follow-up

#2152 chore: remove refs to deprecated io/ioutil
  pkg/cloud/aws/provider_test.go
Labels: opencost, E2, P3, needs-follow-up
