Repository opencost/opencost, pull requests merged in 2023-09, with the labels that each got.

#2141 feat: athena configuration support for Catalog
  pkg/cloud/aws/athenaconfiguration.go
  pkg/cloud/aws/athenaconfiguration_test.go
  pkg/cloud/aws/athenaquerier.go
  pkg/cloud/aws/provider.go
  pkg/cloud/gcp/provider.go
  pkg/cloud/models/models.go
Labels: opencost, P2, kubecost, E2

#2148 Remove non-root user to restore UI
  ui/Dockerfile
  ui/Dockerfile.cross
Labels: opencost, P0, E2

#2159 Linked GitHub teams for Maintainers and Committers.
  MAINTAINERS.md
Labels: opencost, E1, P4

#2163 Revert UI container to 1.105.2 until 1.106.1 is released.
  kubernetes/opencost.yaml
Labels: opencost, P0, E1

#2161 set max results param for athena pagination
  pkg/cloud/aws/athenaquerier.go
Labels: needs cherry pick

#2167 Extend Issues to 360 days and PRs to 90 days
  .github/workflows/stale.yml
Labels: opencost, E1, P4

#2166 Sync Dockerfile and Dockerfile.cross and run as non-root user
  kubernetes/opencost.yaml
  ui/Dockerfile
  ui/Dockerfile.cross
Labels: next release, opencost, P1, v1.107, E2

#2175 Sync Dockerfile and Dockerfile.cross and run as non-root user for 1.106
  ui/Dockerfile
  ui/Dockerfile.cross
Labels: opencost, P0, E2

#2173 Use new filters for sharing
  pkg/costmodel/aggregation.go
  pkg/filter21/ast/walker.go
  pkg/filter21/ast/walker_test.go
  pkg/kubecost/allocation.go
  pkg/kubecost/allocation_test.go
  pkg/kubecost/summaryallocation.go
  pkg/util/filterutil/filterutil.go
Labels: v1.107

#2178 Direct inquiries to Slack and the community meetings rather than Kubecost
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  ROADMAP.md
Labels: opencost, CNCF, E1, P3

#2180 Add "mimir" to info log message
  pkg/cmd/agent/agent.go
  pkg/costmodel/router.go
Labels: P2, E1

#2182 Fix sharing coefficients when unmounted PVs are folded into namespaces
  pkg/kubecost/allocation.go
  pkg/kubecost/summaryallocation.go
  pkg/kubecost/summaryallocation_json.go
  pkg/kubecost/totals.go
  pkg/kubecost/totals_json.go
Labels: v1.107
