Repository opencost/opencost, pull requests merged in 2023-03, with the labels that each got.

#1717 Access warnings on AssetSetRange
  pkg/kubecost/asset.go
Labels: v1.101

#1728 Allow provider regions to be manually configured
  pkg/cloud/aliyunprovider.go
  pkg/cloud/awsprovider.go
  pkg/cloud/azureprovider.go
  pkg/cloud/gcpprovider.go
  pkg/cloud/scalewayprovider.go
  pkg/env/costmodelenv.go
Labels: v1.101

#1739 fix missing cpuprice
  pkg/costmodel/costmodel.go
Labels: needs cherry pick

#1681 Add invalid parameter check support to QueryParams
  pkg/env/env.go
  pkg/util/httputil/httputil.go
  pkg/util/httputil/httputil_test.go
  pkg/util/mapper/mapper.go
Labels: v1.102

#1682 Export v1 Allocation filter params to support validation logic in handlers
  pkg/util/allocationfilterutil/queryfilters.go
Labels: v1.102

#1783 Fix golang.org/x/net CVE with go get -u golang.org/x/net && go mod tidy
  go.mod
  go.sum
Labels: P0, v1.102

#1798 Minor update to API documentation to Include nodes and pods
  docs/swagger.json
Labels: opencost

#1799 Add both amd64 and arm64 support for docker image
  .github/workflows/pr.yaml
Labels: opencost

#1813 Fix CPU max query by using already-existing irate recording rule
  pkg/costmodel/allocation.go
  pkg/prom/diagnostics.go
Labels: needs cherry pick, v1.102
