Repository opencost/opencost, pull requests merged in 2024-10, with the labels that each got.

#2957 Atm/fix windows
  core/pkg/opencost/window.go
  core/pkg/opencost/window_test.go
Labels: needs-follow-up

#2902 Update OCI provider cost metadata
  pkg/cloud/oracle/partnumbers/shape_part_numbers.json
  pkg/cloud/oracle/provider.go
  pkg/cloud/oracle/provider_test.go
  pkg/cloud/oracle/region.go
  pkg/cloud/oracle/region_test.go
Labels: needs-follow-up, JiraCreated

#2828 Minor typos
  spec/opencost-specv01.md
Labels: JiraCreated

#2949 chore: add new region
  pkg/cloud/aws/provider.go
Labels: needs-follow-up

#2956 Implement plugin API upgrades
  pkg/customcost/queryservice_helper.go
  pkg/customcost/repositoryquerier.go
  pkg/customcost/types.go
  pkg/customcost/types_test.go
Labels: needs-follow-up, 1.113

#2959 Cp oci provider metadata
  pkg/cloud/oracle/partnumbers/shape_part_numbers.json
  pkg/cloud/oracle/provider.go
  pkg/cloud/oracle/provider_test.go
  pkg/cloud/oracle/region.go
  pkg/cloud/oracle/region_test.go
Labels: needs-follow-up

#2944 Support openshift in cluster prometheus with kube-rbac-proxy enabled
  pkg/env/costmodelenv.go
  pkg/prom/prom.go
Labels: needs-follow-up

#2952 Add support for Open Telekom Cloud (OTC) provider
  Dockerfile
  Dockerfile.cross
  Dockerfile.debug
  configs/otc.json
  core/pkg/opencost/assetprops.go
  pkg/cloud/otc/provider.go
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/providerconfig.go
Labels: needs-follow-up

#2893 Update path in swagger.json
  docs/swagger.json
Labels: needs-follow-up, JiraCreated

#2771 use AWS price index for Network Loadbalancer hourly costs
  pkg/cloud/aws/provider.go
  pkg/cloud/aws/provider_test.go
  pkg/cloud/aws/testdata/pricing-cn-northwest-1.json
  pkg/cloud/aws/testdata/pricing-us-east-1.json
  pkg/cloud/aws/testdata/pricing-us-east-2.json
Labels: opencost, P2, kubecost, E2, needs-follow-up, JiraCreated

#2968 update go.mod for golang cve
  core/go.mod
  go.mod
Labels: needs-follow-up, v2.4, v1.112

#2953 Nil check on Asset labels before accessing
  core/pkg/opencost/asset_json.go
Labels: needs-follow-up

#2973 use the query window to refresh costs
  pkg/customcost/ingestor.go
Labels: needs-follow-up

#2963 ENG-2914: Introduce GPUUsageMax, isShared and GPU device information
  core/pkg/opencost/allocation.go
  core/pkg/opencost/allocation_json.go
  core/pkg/opencost/bingen.go
  core/pkg/opencost/opencost_codecs.go
  core/pkg/opencost/summaryallocation.go
  core/pkg/opencost/summaryallocation_json.go
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up
