Repository opencost/opencost, pull requests merged in 2024-06, with the labels that each got.

#2767 fix formatting for deduplicated log messages
  core/pkg/log/log.go
Labels: opencost, kubecost, E1, P3, needs-follow-up

#2770 Set docker/login-action to a stable version instead of a SHA
  .github/workflows/build-and-publish-release.yml
Labels: opencost, E1, P3, needs-follow-up

#2766 AWS: use region attribute instead of mapping location
  pkg/cloud/aws/provider.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2763 adds efficiency to return type
  core/pkg/opencost/summaryallocation.go
  core/pkg/opencost/summaryallocation_json.go
Labels: needs-follow-up

#2731 Reintroduce GPU Usage & Efficiency
  core/pkg/opencost/allocation.go
  core/pkg/opencost/allocation_json.go
  core/pkg/opencost/bingen.go
  core/pkg/opencost/opencost_codecs.go
  core/pkg/opencost/summaryallocation.go
  core/pkg/opencost/summaryallocation_json.go
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2239 Updated GCP regions based on "gcloud compute regions list" output
  pkg/cloud/gcp/provider.go
Labels: opencost, P1, kubecost, E2, needs-follow-up

#2282 pkg/costmodel: fix dropped errors
  pkg/costmodel/promparsers.go
Labels: opencost, P2, E2, needs-follow-up

#2776 Remove cloud cost and custom cost from cost model initialization
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
Labels: v1.110

#2775 Fix warn log message for pv
  pkg/costmodel/allocation_helpers.go
Labels: opencost, E1, P3

#2786 memory config controller
  pkg/cloud/config/controller.go
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
Labels: v1.110

#2787 Handle errors from pricing api (#2783)
  pkg/cloud/gcp/provider.go
  pkg/cloud/gcp/provider_test.go
  pkg/cloud/gcp/test/error.json
Labels: v2.3

#2725 Reduce memory consumption
  pkg/clustercache/watchcontroller.go
Labels: needs-follow-up

#2789 Update tests for config controller changes
  pkg/cloud/config/controller_test.go
Labels: v1.110

#2795 run go mod tidy
  go.mod
Labels: v2.3

#2765 ENG-1706 Fix parsing of AWS OnDemand data for certain instance types
  justfile
  pkg/cloud/aws/provider.go
  pkg/cloud/aws/provider_test.go
Labels: needs-follow-up

#2807 Update deps dependabot
  go.mod
  go.sum
Labels: needs-follow-up

#2804 Handle partitioned and updating billing exports (#2794) ENG-111
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
Labels: v2.3, v2.3.2
