Repository opencost/opencost, pull requests merged in 2024-07, with the labels that each got.

#2837 Separate results of container_fs queries by device and use largest de…
  pkg/costmodel/cluster.go
Labels: v2.3

#2842 Create matchable azure local disk provider id's
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/provider_test.go
  pkg/costmodel/cluster.go
Labels: v2.3

#2846 Fix local storage queries
  pkg/costmodel/cluster.go
Labels: needs-follow-up, v2.3, v2.4

#2844 Allocation/Allocation Summary Idle
  core/pkg/opencost/allocation.go
  core/pkg/opencost/allocation_json.go
  core/pkg/opencost/summaryallocation.go
  core/pkg/opencost/summaryallocation_json.go
Labels: needs-follow-up

#2841 Set timeout for Azure rate-card api call
  pkg/cloud/azure/provider.go
Labels: opencost, kubecost, E1, P3

#2835 Expose shareIdle parameter in public API
  pkg/costmodel/aggregation.go
  pkg/costmodel/costmodel.go
Labels: enhancement, opencost, doc needed, E2, P3
