Repository opencost/opencost, pull requests merged in 2024-02, with the labels that each got.

#2496 update AWS SDK to latest
  go.mod
  go.sum
Labels: needs-follow-up

#2497 Saweber/2.0 aws sdk
  go.mod
  go.sum
Labels: needs-follow-up

#2500 Fix UI Build Command in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: needs-follow-up

#2499 use `policy/v1` for `PodDisruptionBudget`
  pkg/clustercache/clustercache.go
  pkg/clustercache/clusterexporter.go
  pkg/clustercache/clusterimporter.go
Labels: opencost, P1, kubecost, E2, needs-follow-up

#2509 fix csv casing, precedence, add test
  configs/pricing_schema_mixed_gpu_ondemand.csv
  pkg/cloud/provider/csvprovider.go
  test/cloud_test.go
Labels: needs-follow-up

#2512 fix float issues
  test/cloud_test.go
Labels: needs-follow-up

#2513 fix float issues
  test/cloud_test.go
Labels: needs-follow-up

#2502 Third party attributions in opencost artifacts
  CONTRIBUTING.md
  Dockerfile
  Dockerfile.cross
  THIRD_PARTY_LICENSES.txt
  ui/Dockerfile
  ui/Dockerfile.cross
  ui/justfile
Labels: opencost, CNCF, P1, E2, needs-follow-up

#2517 support missing instance_type labels for onprem
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2519 chore: opencost-helm-chart #176 issue consistent prometheus namespaceName and serviceName
  kubernetes/exporter/opencost-exporter.yaml
  kubernetes/opencost.yaml
  ui/README.md
Labels: needs-follow-up

#2521 Allow opencost-ui to run with a read-only root filesystem
  ui/Dockerfile
  ui/Dockerfile.cross
  ui/docker-entrypoint.sh
Labels: opencost, P1, E2, needs-follow-up

#2479 Add version rendered at bottom of page.
  ui/docker-entrypoint.sh
  ui/package-lock.json
  ui/package.json
  ui/src/Reports.js
  ui/src/cloudCostReports.js
  ui/src/components/Footer.js
Labels: opencost, P2, E1, needs-follow-up

#2529 AllocationFilterParser: Add 'nilable' to controller/controllerKind props
  core/pkg/filter/allocation/parser.go
Labels: needs-follow-up

#2522 Tweak OCI URL for container image labels
  Dockerfile
  Dockerfile.cross
  ui/Dockerfile
  ui/Dockerfile.cross
Labels: needs-follow-up

#2531 wipe out dead code, fix build
  pkg/costmodel/csv_export.go
Labels: needs-follow-up

#2523 Ajay tripathy fix gpucost
  pkg/cloud/provider/csvprovider.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2532 wipe out dead code, fix build
  pkg/costmodel/csv_export.go
Labels: needs-follow-up

#2533 Cp 109 gpucost
  pkg/cloud/provider/csvprovider.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2535 Azure cloud costs: Add IsAzureDownloadBillingDataToDisk
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up

#2494 workflow for opencost builds
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2539 step outputs rather than ev var
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2536 Support LB and PV item-level reconciliation
  core/pkg/opencost/allocation.go
Labels: next release, needs-follow-up

#2541 Pick of #2536 for v2.1
  core/pkg/opencost/allocation.go
Labels: needs-follow-up

#2543 Suppress undesirable provider error log
  pkg/cloud/config/controller.go
Labels: needs-follow-up

#2542 Add `statefulset`, `daemonset`, and `job` to drop-down options
  ui/src/Reports.js
Labels: needs-follow-up

#2534 More defensive approach to retrieving Node labels for a node
  pkg/costmodel/cluster_helpers.go
Labels: needs-follow-up

#2551 Pick #2534 for v2.0
  pkg/costmodel/cluster_helpers.go
Labels: needs-follow-up

#2553 update azure sdk versions
  go.mod
  go.sum
  pkg/cloud/azure/storageauthorizer.go
Labels: needs-follow-up

#2555 Fix default of 7 days so it doesn't report 'Custom' date range
  ui/src/Reports.js
Labels: opencost, E1, P3, needs-follow-up

#2557 Add support for showing "__idle__" in the UI
  ui/src/services/allocation.js
Labels: opencost, P2, E1, needs-follow-up

#2556 Replaced Kubecost messaging with OpenCost specifics
  ui/src/Reports.js
  ui/src/cloudCost/cloudCostDetails.js
Labels: opencost, E1, P3, needs-follow-up

#2558 remove env check
  pkg/cloud/config/controller_handlers.go
Labels: needs-follow-up

#2561 enable extra debugging for buildx in the GHA
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2562 add support for EKS pod identities
  go.mod
  go.sum
Labels: needs-follow-up

#2563 Update workflow build
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2574 trigger build and release from tag
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2569 impl basic structs for plugins
  core/pkg/model/custom_cost_request.go
  core/pkg/model/custom_cost_response.go
Labels: needs-follow-up

#2570 Switch from JSON to protobuf for kube-api requests
  pkg/kubeconfig/loader.go
Labels: needs-follow-up

#2576 Fix pod cache initialization
  pkg/clustercache/clustercache.go
Labels: opencost, P2, kubecost, E1, needs-follow-up

#2580 add release to v1.109
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2581 fix build version detect
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2585 update tags
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2586 CP back changes for tagging update in 109
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2588 cost-model was missing the build-args for version and commit
  justfile
Labels: needs-follow-up

#2587 cost-model was missing the build-args for version and commit
  justfile
Labels: needs-follow-up

#2590 add release number to build
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2589 Add release number
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2591 Standardize RELEASE_VERSION and IMAGE_TAG across build scripts
  .github/workflows/build-and-publish-release.yml
  justfile
  ui/justfile
Labels: needs-follow-up

#2596 The version.go moved and the new location is in 'core'
  justfile
Labels: needs-follow-up

#2571 Add version and commit for logging
  Dockerfile.cross
Labels: needs-follow-up

#2566 go mod tidy
  go.sum
Labels: needs-follow-up

#2578 skip custom pricing if empty string
  pkg/cloud/models/models.go
  pkg/cloud/models/models_test.go
Labels: needs-follow-up

#2560 Add comments and logging to pkg/cloud
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/config/controller.go
Labels: needs-follow-up

#2579 Atm/plugin types
  core/go.mod
  core/go.sum
  core/pkg/model/custom_cost_request.go
  core/pkg/model/customcostrequest.go
  core/pkg/model/customcostresponse.go
  core/pkg/plugin/plugin_interface.go
  go.mod
  go.sum
Labels: needs-follow-up
