Repository opencost/opencost, pull requests merged in 2024-05, with the labels that each got.

#2713 Update CloudCost service categorization for AWS
  pkg/cloud/aws/athenaquerier.go
Labels: needs-follow-up

#2728 check for licensing fee in in meter category when assigning category
  pkg/cloud/azure/billingexportparser.go
Labels: needs-follow-up, v2.2

#2729 check for licensing fee in in meter category when assigning category
  pkg/cloud/azure/billingexportparser.go
Labels: needs-follow-up, v2.2

#2730 Buffer Read/Write Symmetry Fix
  core/pkg/util/buffer.go
  core/pkg/util/buffer_test.go
Labels: needs-follow-up

#2734 Prevent prefix from being applied twice to files
  pkg/storage/prefixedbucketstorage.go
Labels: needs-follow-up

#2735 Prevent prefix from being applied twice to files
  pkg/storage/prefixedbucketstorage.go
Labels: needs-follow-up, v2.2

#2717 demoted s3 commands to trace
  pkg/storage/s3storage.go
  pkg/storage/storage.go
Labels: needs-follow-up

#2691 remove cloud cost and custom cost from cost-model initialization
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
Labels: needs-follow-up, v2.3

#2726 Add Alex Meijer as a new Maintainer.
  MAINTAINERS.md
Labels: needs-follow-up

#2739 Update AWS web identity type string
  pkg/cloud/aws/authorizer.go
Labels: needs-follow-up, v2.3

#2743 return default resource rates for suse rancher nodes
  pkg/costmodel/costmodel.go
Labels: needs-follow-up

#2745 WIP SWII Cloud Costs
  pkg/cloud/config/controller_handlers.go
  pkg/cloud/config/utils.go
  pkg/cloud/config/watcher.go
  pkg/cloudcost/ingestionmanager.go
  pkg/cloudcost/ingestor.go
  pkg/cloudcost/repositoryfactory.go
Labels: needs-follow-up

#2741 Removing the UI code, the new repository is opencost/opencost-ui
  .github/ISSUE_TEMPLATE/opencost-bug-report.md
  .github/dependabot.yml
  .github/workflows/build-and-publish-release.yml
  .github/workflows/build-test.yaml
  .gitignore
  README.md
  ui/.babelrc
  ui/.dockerignore
  ui/.nvmrc
  ui/Dockerfile
  ui/Dockerfile.cross
  ui/Dockerfile.debug
  ui/README.md
  ui/default.nginx.conf.template
  ui/docker-entrypoint.sh
  ui/justfile
  ui/nginx.conf
  ui/package-lock.json
  ui/package.json
  ui/src/Reports.js
  ui/src/app.js
  ui/src/cloudCost/cloudCost.js
  ui/src/cloudCost/cloudCostChart/index.js
  ui/src/cloudCost/cloudCostChart/rangeChart.js
  ui/src/cloudCost/cloudCostDetails.js
  ui/src/cloudCost/cloudCostRow.js
  ui/src/cloudCost/controls/cloudCostEditControls.js
  ui/src/cloudCost/tokens.js
  ui/src/cloudCostReports.js
  ui/src/components/AllocationChart/RangeChart.js
  ui/src/components/AllocationChart/SummaryChart.js
  ui/src/components/AllocationChart/index.js
  ui/src/components/Controls/Download.js
  ui/src/components/Controls/Edit.js
  ui/src/components/Controls/index.js
  ui/src/components/Details.js
  ui/src/components/Footer.js
  ui/src/components/Header.js
  ui/src/components/Nav/NavItem.js
  ui/src/components/Nav/SidebarNav.js
  ui/src/components/Nav/index.js
  ui/src/components/Page.js
  ui/src/components/SelectWindow.js
  ui/src/components/Subtitle.js
  ui/src/components/Warnings.js
  ui/src/components/allocationReport.js
  ui/src/constants/colors.js
  ui/src/constants/currencyCodes.js
  ui/src/css/index.css
  ui/src/images/favicon.ico
  ui/src/images/logo.png
  ui/src/index.html
  ui/src/opencost-ui.png
  ui/src/route.js
  ui/src/services/allocation.js
  ui/src/services/cloudCostDayTotals.js
  ui/src/services/cloudCostTop.js
  ui/src/thumbnail.png
  ui/src/util.js
Labels: needs-follow-up

#2434 Enable Custom Pricing Provider in OpenCost for Public Cloud Kubernetes Clusters
  pkg/cloud/provider/provider.go
  pkg/env/costmodelenv.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2760 GCP Cloud Costs resource name fallback
  pkg/cloud/gcp/bigqueryintegration.go
  pkg/cloud/gcp/bigqueryintegration_types.go
  pkg/cloud/gcp/bigqueryintegration_types_test.go
Labels: needs-follow-up

#2724 Ajay tripathy alibaba improvements
  pkg/cloud/alibaba/provider.go
  pkg/cloud/alibaba/provider_test.go
Labels: needs-follow-up

#2719 initial pass of a whitelist that adds labels relevant for aggregation
  pkg/metrics/metricsconfig.go
  pkg/metrics/podlabelmetrics.go
  pkg/metrics/podlabelmetrics_test.go
Labels: needs-follow-up

#2441 Add config option to not query for local disk cost
  pkg/costmodel/cluster.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up
