Repository opencost/opencost, pull requests merged in 2024-04, with the labels that each got.

#2666 move context to first argument
  pkg/cloudcost/querier.go
  pkg/cloudcost/queryservice.go
  pkg/cloudcost/queryservice_helper.go
  pkg/cloudcost/repositoryquerier.go
Labels: needs-follow-up

#2684 properly trim quotes and prefix for label
  pkg/cloud/aws/athenaintegration.go
Labels: needs-follow-up, v2.2

#2685 V2.2 patch/fix aws label trimming cherry pick
  pkg/cloud/aws/athenaintegration.go
Labels: needs-follow-up, v2.2

#2678 BYO prometheus , common prometheus docs broken links fixed
  pkg/prom/diagnostics.go
  pkg/prom/helpers.go
Labels: opencost, doc needed, P2, E1, needs-follow-up

#2634 Adding additional check for EKS, using Kubelet
  pkg/cloud/provider/provider.go
Labels: opencost, P2, kubecost, E1, needs-follow-up

#2686 Exposed `GetKubecostContainers()`
  pkg/costmodel/router.go
Labels: needs-follow-up

#2688 cloud cost status returns empty slice instead of nil
  pkg/cloudcost/pipelineservice.go
Labels: needs-follow-up, v2.2

#2687 cloud cost status returns empty slice instead of nil
  pkg/cloudcost/pipelineservice.go
Labels: needs-follow-up, v2.2

#2690 Cherry pick #2686
  pkg/costmodel/router.go
Labels: needs-follow-up

#2693 prevent spam log in unconfigured cloudcost
  pkg/cloud/config/controller.go
Labels: needs-follow-up, v2.2

#2694 prevent spam log in unconfigured cloudcost
  pkg/cloud/config/controller.go
Labels: needs-follow-up, v2.2

#2700 Create a hash key when agg properties are not set for Cloud Cost
  core/pkg/opencost/cloudcost.go
  core/pkg/opencost/cloudcostprops.go
  core/pkg/opencost/cloudcostprops_test.go
Labels: needs-follow-up, v2.2

#2701 Add hash key for saving cloud cost
  core/pkg/opencost/cloudcostprops.go
  core/pkg/opencost/cloudcostprops_test.go
Labels: needs-follow-up, v2.2

#2707 TypeUtil Enhancements
  core/go.mod
  core/go.sum
  core/pkg/util/typeutil/typeutil.go
  core/pkg/util/typeutil/typeutil_test.go
Labels: needs-follow-up

#2711 Azure Blob Stream Reader
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
  pkg/cloud/azure/streamreader.go
Labels: needs-follow-up

#2718 Update Maintainers
  MAINTAINERS.md
Labels: needs-follow-up

#2722 Azure Stream Reader Bug Fix
  pkg/cloud/azure/streamreader.go
Labels: needs-follow-up

#2715 Bump logging from WARN down to DEBUG in `getContainerAllocation()`
  pkg/costmodel/costmodel.go
Labels: needs-follow-up

#2710 AWS IRSA authorizer for cloud integrations
  pkg/cloud/aws/authorizer.go
  pkg/cloud/aws/authorizer_test.go
  pkg/cloud/aws/webidentity.go
Labels: needs-follow-up
