Repository opencost/opencost, pull requests merged in 2024-01, with the labels that each got.

#2301 Set configs in `aws.json` to empty strings
  configs/aws.json
Labels: needs-follow-up

#2429 Make FileStorage's Read and Write go through `flock()`
  pkg/storage/filestorage.go
  pkg/util/fileutil/fileutil.go
  pkg/util/fileutil/locks_test.go
  pkg/util/fileutil/locks_unix.go
  pkg/util/fileutil/locks_windows.go
Labels: needs-follow-up

#2386 Fix aws spot price with default config
  pkg/cloud/aws/provider.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2432 Fix a test that relies on Prom library
  pkg/kubecost/window_test.go
Labels: needs-follow-up

#2447 gpu slicing
  pkg/cloud/models/models.go
  pkg/costmodel/costmodel.go
  pkg/costmodel/metrics.go
Labels: needs-follow-up

#2458 Add trace log level (Trace and Tracef) to the log package
  core/pkg/log/log.go
Labels: needs-follow-up

#2456 Download Azure billing CSV to filesystem, instead of holding in memory
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
Labels: needs-follow-up

#2317 Cloud Costs Kubernetesless
  pkg/cloud/config/controller.go
  pkg/cloud/config/watcher.go
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
  pkg/env/costmodelenv.go
  pkg/env/costmodelenv_test.go
Labels: next release, opencost, P2, E2, needs-follow-up

#2461 [Opencost-Core] Parse CloudCostProperty
  core/pkg/opencost/cloudcostprops.go
  pkg/cloudcost/queryservice_helper.go
Labels: needs-follow-up

#2367 Oracle Cloud Infrastructure (OCI) Provider
  Dockerfile
  Dockerfile.cross
  configs/oracle.json
  core/pkg/opencost/assetprops.go
  pkg/cloud/oracle/key.go
  pkg/cloud/oracle/partnumbers/shape_part_numbers.json
  pkg/cloud/oracle/product.go
  pkg/cloud/oracle/provider.go
  pkg/cloud/oracle/provider_test.go
  pkg/cloud/oracle/ratecard.go
  pkg/cloud/oracle/ratecard_test.go
  pkg/cloud/oracle/region.go
  pkg/cloud/oracle/test/prices_usd.json
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/providerconfig.go
  pkg/env/costmodelenv.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2467 [Opencost-Core] Fix the Dockerfile and Makefile
  Dockerfile
  Makefile
Labels: needs-follow-up

#2143 feat: add oci annotations to container images
  Dockerfile
  Dockerfile.cross
  ui/Dockerfile
  ui/Dockerfile.cross
Labels: opencost, E2, P3, needs-follow-up

#2471 Add OpenSSF Best Practices badge to README
  README.md
Labels: opencost, CNCF, P2, E1, needs-follow-up

#2469 Fix 'go vet' warning "loop variable r captured by func literal"
  pkg/cloud/aws/provider.go
Labels: opencost, P2, E1, needs-follow-up

#2474 avoid nil panic when seaching for GPU costs in non-existent nodes
  pkg/costmodel/metrics.go
Labels: needs-follow-up

#2312 Simplify GPU query
  pkg/costmodel/costmodel.go
Labels: opencost, P2, kubecost, E3, needs-follow-up

#2478 Cross-Zone and Cross-Region Network Costs Labels
  pkg/costmodel/allocation.go
Labels: needs-follow-up

#2485 Pick #2478 for v2.0
  pkg/costmodel/allocation.go
Labels: needs-follow-up

#2313 Stop emitting unused metrics
  pkg/costmodel/metrics.go
  pkg/env/costmodelenv.go
  pkg/metrics/kubemetrics.go
Labels: opencost, P2, kubecost, E3, needs-follow-up

#2476 Make field map access concurrency-safe
  core/pkg/filter/allocation/parser.go
  core/pkg/filter/asset/parser.go
  core/pkg/filter/cloudcost/parser.go
Labels: needs-follow-up

#2488 address resolve endpoint issue w/AWS
  go.mod
  go.sum
Labels: needs-follow-up

#2489 Merge pull request #2488 from ameijer/atm/aws-sdk-version
  go.mod
  go.sum
Labels: needs-follow-up

#2490 Remove label sanitation from cloud cost agg property parsing
  core/pkg/opencost/cloudcostprops.go
Labels: needs-follow-up

#2491 Remove label sanitation from cloud cost agg property parsing
  core/pkg/opencost/cloudcostprops.go
Labels: needs-follow-up

#2493 LbAllocation Hours
  core/pkg/opencost/allocation.go
  core/pkg/opencost/bingen.go
  core/pkg/opencost/opencost_codecs.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2466 Update NOTICE for 2024
  NOTICE
Labels: opencost, CNCF, E1, P4, needs-follow-up

#2470 Add 'go vet' to testing
  CONTRIBUTING.md
  justfile
Labels: opencost, CNCF, P2, E1, needs-follow-up, v1.109

#2487 Dependabot UI roll-up
  ui/package-lock.json
  ui/package.json
Labels: opencost, P1, E1, needs-follow-up
