Repository opencost/opencost, pull requests merged in 2024-09, with the labels that each got.

#2908 Revert "bump dependencies for CVE."
  go.mod
  go.sum
Labels: needs-follow-up

#2896 handle aws generated tags
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/s3selectintegration.go
Labels: needs-follow-up

#2909 handle aws generated tags (#2896)
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/s3selectintegration.go
Labels: v2.4

#2911 OCI cloud costs integration (#2870)
  .gitignore
  go.mod
  go.sum
  pkg/cloud/config/configurations.go
  pkg/cloud/config/statuses.go
  pkg/cloud/oracle/authorizer.go
  pkg/cloud/oracle/usageapiconfiguration.go
  pkg/cloud/oracle/usageapiconfiguration_test.go
  pkg/cloud/oracle/usageapiintegration.go
  pkg/cloud/oracle/usageapiintegration_test.go
  pkg/cloudcost/integration.go
Labels: v2.4

#2917 add connection statuses
  pkg/cloud/oracle/usageapiintegration.go
Labels: needs-follow-up, v2.4

#2918 add connection statuses
  pkg/cloud/oracle/usageapiintegration.go
Labels: v2.4

#2920 Fixes /savings/orphanedResources end point failing with 500 internal server when its unable to read disk.description
  pkg/cloud/gcp/provider.go
Labels: needs-follow-up

#2926 update MAINTAINERS
  MAINTAINERS.md
Labels: needs-follow-up

#2930 ENG-2837 - Efficiency Calculations
  core/pkg/opencost/allocation.go
Labels: needs-follow-up

#2936 fix release script, make relative repo for better testing in fork
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#2940 Make logs more testable
  core/pkg/log/log.go
  core/pkg/log/log_test.go
Labels: needs-follow-up
