Repository opencost/opencost, pull requests merged in 2024-08, with the labels that each got.

#2854 [v2.3] Fix local storage queries
  pkg/costmodel/cluster.go
Labels: v2.3

#2863 Remove extra group by args for query
  pkg/cloud/gcp/bigqueryintegration.go
Labels: v2.4

#2864 Remove extra group by args for query (#2863)
  pkg/cloud/gcp/bigqueryintegration.go
Labels: v2.3

#2861 Sth/expand cloud cost properties
  core/pkg/filter/cloudcost/fields.go
  core/pkg/filter/cloudcost/parser.go
  core/pkg/filter/cloudcost/parser_test.go
  core/pkg/filter/fieldstrings/fieldstrings.go
  core/pkg/opencost/bingen.go
  core/pkg/opencost/cloudcost.go
  core/pkg/opencost/cloudcostmatcher.go
  core/pkg/opencost/cloudcostprops.go
  core/pkg/opencost/cloudcostprops_test.go
  core/pkg/opencost/opencost_codecs.go
  pkg/cloud/aws/athenaintegration.go
  pkg/cloud/aws/s3selectintegration.go
  pkg/cloud/aws/s3selectquerier.go
  pkg/cloud/azure/azurestorageintegration.go
  pkg/cloud/azure/billingexportparser.go
  pkg/cloud/azure/resources/billingexports/values/MissingBrackets.csv
  pkg/cloud/azure/resources/billingexports/values/Template.csv
  pkg/cloud/azure/resources/billingexports/values/VirtualMachine.csv
  pkg/cloud/gcp/bigqueryintegration.go
  pkg/cloud/gcp/bigqueryintegration_test.go
  pkg/cloud/gcp/bigqueryintegration_types.go
Labels: v2.4

#2865 V2.3 patch/local disk updates
  pkg/cloud/provider/provider.go
  pkg/cloud/provider/provider_test.go
  pkg/costmodel/cluster.go
Labels: v2.3

#2853 Swap `DCGM_FI_DEV_GPU_UTIL` for `DCGM_FI_PROF_GR_ENGINE_ACTIVE`.
  pkg/costmodel/allocation.go
  pkg/costmodel/allocation_helpers.go
Labels: needs-follow-up

#2858 Fix the issue where the prices for most Alibaba Cloud instance types are incorrect when the instance family generation number is greater than or equal to 7
  pkg/cloud/alibaba/provider.go
  pkg/cloud/alibaba/provider_test.go
Labels: needs-follow-up

#2862 Correctly calculate `gpuCost` when the `"nvidia.com/gpu.replicas"` label is present.
  pkg/costmodel/costmodel.go
  pkg/costmodel/costmodel_test.go
Labels: needs-follow-up

#2882 ENG-136: Exclude local storage provisioner by sig-storage-local-provisioner on node to show up in assets when param ASSET_INCLUDE_LOCAL_DISK_COST is set to false
  pkg/costmodel/cluster.go
  pkg/costmodel/cluster_test.go
Labels: needs-follow-up

#2857 Add lock on file check and download so that partially downloaded file…
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
  pkg/cloudcost/integration.go
Labels: needs-follow-up, v2.4

#2894 Add lock on file check and download so that partially downloaded file…
  pkg/cloud/azure/storagebillingparser.go
  pkg/cloud/azure/storageconnection.go
  pkg/cloudcost/integration.go
Labels: v2.4

#2870 OCI cloud costs integration
  .gitignore
  go.mod
  go.sum
  pkg/cloud/config/configurations.go
  pkg/cloud/config/statuses.go
  pkg/cloud/oracle/authorizer.go
  pkg/cloud/oracle/usageapiconfiguration.go
  pkg/cloud/oracle/usageapiconfiguration_test.go
  pkg/cloud/oracle/usageapiintegration.go
  pkg/cloud/oracle/usageapiintegration_test.go
  pkg/cloudcost/integration.go
Labels: needs-follow-up
