Repository opencost/opencost, pull requests merged in 2024-03, with the labels that each got.

#2567 use status/buildinfo endpoint to get status instead of status/config added variable to set static scrape interval
  pkg/cmd/agent/agent.go
  pkg/costmodel/router.go
  pkg/env/costmodelenv.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2602 cherry pick over
  core/pkg/model/customcostresponse.go
  core/pkg/version/version.go
  justfile
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
  pkg/customcost/ingestor.go
  pkg/customcost/memoryrepository.go
  pkg/customcost/pipelineservice.go
  pkg/customcost/repository.go
  pkg/customcost/status.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up

#2603 continued custom cost ingest impl
  go.mod
  go.sum
  pkg/customcost/ingestor.go
  pkg/customcost/memoryrepository.go
  pkg/customcost/pipelineservice.go
  pkg/customcost/repository.go
Labels: needs-follow-up

#2428 refactor and improve tilt
  .gitignore
  Dockerfile.debug
  Tiltfile
  Tiltfile.opencost
  tilt-values.yaml
  ui/Dockerfile.debug
Labels: needs-follow-up

#2564 Set package repository to ghcr.io
  kubernetes/opencost.yaml
Labels: needs-follow-up

#2609 Version logging for the develop branch
  justfile
Labels: needs-follow-up

#2610 Atm/plugin ingestion
  pkg/customcost/ingestor.go
  pkg/customcost/pipelineservice.go
  pkg/customcost/pipelineservice_test.go
  pkg/customcost/status.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up

#2611 merge working branch from develop
  .github/workflows/build-and-publish-release.yml
  .gitignore
  Dockerfile.debug
  Tiltfile
  Tiltfile.opencost
  justfile
  kubernetes/opencost.yaml
  pkg/customcost/pipelineservice.go
  tilt-values.yaml
  ui/Dockerfile.debug
  ui/justfile
Labels: needs-follow-up

#2614 Atm/protobuf usage
  core/pkg/model/customcost_helpers.go
  core/pkg/model/customcostrequest.go
  core/pkg/model/customcostresponse.go
  core/pkg/model/pb/messages.pb.go
  core/pkg/model/pb/messages_grpc.pb.go
  core/pkg/plugin/grpc.go
  core/pkg/plugin/plugin_interface.go
  pkg/customcost/ingestor.go
  pkg/customcost/pipelineservice.go
  protos/customcost/messages.proto
Labels: needs-follow-up

#2616 pass by ptr to pass govet
  core/pkg/plugin/grpc.go
  core/pkg/plugin/plugin_interface.go
Labels: needs-follow-up

#2620 impl intersection logic, move instantiation to common KCM code to unb…
  pkg/cmd/costmodel/costmodel.go
  pkg/costmodel/router.go
  pkg/customcost/memoryrepository.go
  pkg/customcost/props.go
  pkg/customcost/types.go
Labels: needs-follow-up

#2618 Changed err log to info log for csv node pricing
  pkg/cloud/provider/csvprovider.go
Labels: needs-follow-up

#2625 merge in from develop
  .github/workflows/build-test.yaml
  core/pkg/model/pb/messages.pb.go
  core/pkg/model/pb/messages_grpc.pb.go
  justfile
  pkg/cloud/provider/csvprovider.go
  pkg/costmodel/router.go
  pkg/customcost/ingestor.go
  pkg/customcost/memoryrepository.go
  pkg/customcost/pipelineservice.go
  pkg/customcost/repository.go
  pkg/customcost/repositoryquerier.go
  pkg/customcost/status.go
Labels: needs-follow-up

#2626 omit empty fix
  pkg/customcost/status.go
Labels: needs-follow-up

#2627 Final plugin fixes
  justfile
  pkg/costmodel/router.go
Labels: needs-follow-up

#2622 feat: add missing azs to Scaleway provider
  pkg/cloud/scaleway/provider.go
Labels: needs-follow-up

#2630 provide default accumulation for custom costs API
  pkg/customcost/repositoryquerier.go
  pkg/customcost/repositoryquerier_test.go
Labels: needs-follow-up

#2629 Add aggregations and filtering to OC plugins
  pkg/customcost/matcher.go
  pkg/customcost/parser.go
  pkg/customcost/props.go
  pkg/customcost/queryservice_helper.go
  pkg/customcost/repositoryquerier.go
  pkg/customcost/types.go
Labels: needs-follow-up

#2633 Add CostSource to CustomCost responses, aggregations, and filtering.
  pkg/customcost/matcher.go
  pkg/customcost/parser.go
  pkg/customcost/props.go
  pkg/customcost/types.go
Labels: needs-follow-up

#2631 Create a filter implementation for K8s `runtime.Object`s
  core/pkg/filter/allocation/fields.go
  core/pkg/filter/asset/fields.go
  core/pkg/filter/cloudcost/fields.go
  core/pkg/filter/fieldstrings/fieldstrings.go
  core/pkg/filter/k8sobject/fields.go
  core/pkg/filter/k8sobject/parser.go
  core/pkg/filter/ops/ops.go
  core/pkg/opencost/k8sobjectmatcher.go
  core/pkg/opencost/k8sobjectmatcher_test.go
Labels: needs-follow-up

#2639 use retention to determine coverage, not query window
  pkg/customcost/repositoryquerier.go
  pkg/env/costmodelenv.go
Labels: needs-follow-up

#2605 minor consistency update for node's well known labels
  core/pkg/util/compat.go
  pkg/cloud/oracle/provider_test.go
  test/cloud_test.go
Labels: opencost, P2, kubecost, E2, needs-follow-up

#2654 Wrap unknown tag columns in double qotes
  pkg/cloud/aws/athenaintegration.go
Labels: needs-follow-up

#2660 Remove headers from errors
  pkg/prom/query.go
Labels: needs-follow-up, v2.2

#2661 Remove headers from errors
  pkg/prom/query.go
Labels: needs-follow-up

#2662 Update azure storage, add bucket storage tests, s3 storage fix
  go.mod
  go.sum
  pkg/storage/azurestorage.go
  pkg/storage/bucketstorage_test.go
  pkg/storage/s3storage.go
Labels: needs-follow-up, v2.2

#2656 Sth/azure storage upgrade
  go.mod
  go.sum
  pkg/storage/azurestorage.go
  pkg/storage/bucketstorage_test.go
  pkg/storage/s3storage.go
Labels: needs-follow-up, v2.2

#2659 Custom Costs Migration
  pkg/customcost/repositoryquerier.go
  pkg/customcost/repositoryquerier_test.go
Labels: needs-follow-up

#2663 Update the `/installInfo` endpoint
  pkg/costmodel/router.go
Labels: needs-follow-up

#2667 [cherry-pick] Update the /installInfo endpoint
  pkg/costmodel/router.go
Labels: needs-follow-up

#2671 Fix Custom Cost window and step calculations
  pkg/customcost/querier.go
  pkg/customcost/repositoryquerier.go
  pkg/customcost/repositoryquerier_test.go
Labels: needs-follow-up

#2672 #2671 Cherry Pick
  pkg/customcost/querier.go
  pkg/customcost/repositoryquerier.go
Labels: needs-follow-up

#2670 Update `/installInfo` endpoint. Adds startTime back in.
  pkg/costmodel/router.go
Labels: needs-follow-up

#2674 [cherry-pick] Update /installInfo endpoint. Adds startTime back in.
  pkg/costmodel/router.go
Labels: needs-follow-up

#2675 Fix test results
  pkg/customcost/repositoryquerier_test.go
Labels: needs-follow-up, v2.2

#2676 Add `domains` to `/customCost/status` response
  pkg/customcost/pipelineservice.go
  pkg/customcost/status.go
Labels: needs-follow-up

#2677 Add `domains` to `/customCost/status` response (#2676)
  pkg/customcost/pipelineservice.go
  pkg/customcost/status.go
Labels: needs-follow-up
