Repository opencost/opencost, pull requests merged in 2025-03, with the labels that each got.

#3057 bump go version 1.23.5
  go.mod
Labels: needs cherry pick, needs-follow-up, LTS

#3080 Network Insights to OpenCost Core
  core/pkg/filter/networkinsight/fields.go
  core/pkg/filter/networkinsight/parser.go
  core/pkg/opencost/bingen.go
  core/pkg/opencost/mock.go
  core/pkg/opencost/networkinsight.go
  core/pkg/opencost/networkinsight_test.go
  core/pkg/opencost/networkinsightgraph.go
  core/pkg/opencost/networkinsightmatcher.go
  core/pkg/opencost/opencost_codecs.go
Labels: needs-follow-up

#3081 test out container building
  .github/actions/build-container/action.yaml
  .github/workflows/build-and-publish-develop.yml
  .github/workflows/build-and-publish-release.yml
Labels: needs-follow-up

#3085 fix duplicate labels error in emitted metrics
  pkg/clustercache/store.go
Labels: needs-follow-up, 1.115
